services:

  postgres:

    image: postgres:16

    container_name: meupet-postgres

    restart: always

    environment:
      POSTGRES_USER: meupet
      POSTGRES_PASSWORD: meupet123
      POSTGRES_DB: meupet_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
